server:
 port: 8323
 

spring:
 application:
  name: clg-student
 
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8061/eureka/ 
  instance:
   hostname: localhost
  
    
     

 
 
 